### ISSUE TITLE
Minor glitch in UI after startup and super-left

### ISSUE THREAD

**Issue by petrisch** [AaronErhardt/tuxedo-rs#10]
Maybe its an upstream thing and I probably should do a video.

When I open the app first and put it to the left side of the screen,
then hover the mouse over the title bar,
I see a flicker on the right side of the window.
As if there was a scrollbar getting enabled/disabled quickly.

If however I put the app first to the right side of the screen,
and then left, the issue is gone.

This is on a aura 1 with ubuntu 20.04, the flatpak version.
And yay it doesn't really bother :smile:

**Comment by AaronErhardt** [comment]
Mhh, I can't reproduce. A video would be helpful.

I the issue dependent on the window size? In any case, this rather sounds like a but in GTK.
