### ISSUE TITLE
Support uniwill hardware

### ISSUE THREAD

**Issue by crisidev** [AaronErhardt/tuxedo-rs#3]
Related to #2.

Since I have a Pulse 14 Gen 1, based on uniwill, I'll be working on a PR to support this hw family.

I have already something that is able to print the fan speed, so it's all downhill from here :)

**Comment by crisidev** [comment]
I found out after a while one of the suspend channel is erroring out:

```
ERROR tux_tailord::suspend: Error receiving suspend message: `channel closed`
```

and I not sure if it is my patch or anything to do with the event loop..

**Comment by AaronErhardt** [comment]
Can you run tailord with `RUST_BACKTRACE=1`? 
Also, maybe your system has no `org.freedesktop.login1.Manager` DBUS service, which is currently used to detect a suspend event.

**Comment by crisidev** [comment]
Right.. I use gnome + i3, so I think the closest thing I have is `org.gnome.SessionManager`.

**Comment by crisidev** [comment]
Running with `RUST_BACKTRACE=1` does not help because it does not crash, it continue printing the error

```
ERROR tux_tailord::suspend: Error receiving suspend message: `channel closed`
```

**Comment by AaronErhardt** [comment]
I didn't find this error message in the code though... Do you have an idea where the error is caused?

**Comment by crisidev** [comment]
It comes from here: https://github.com/AaronErhardt/tuxedo-rs/blob/main/tailord/src/suspend.rs#L48

**Comment by crisidev** [comment]
I think what is happening is that it is never notifying systemd that the service is ready because it is stuck somethere and in fact signals do not work for me.

**Comment by AaronErhardt** [comment]
I also had problems while installing tailord on another system. Somehow, it never really started and maybe it also had something to do with systemd. It runs fine though on my machine since several months, but maybe I've overlooked something necessary for fresh installs.

**Comment by crisidev** [comment]
Can you try something for me? If you start tailord and then run `kill -INT pid-of-tailord` is the signal caught by the main handler and the program stopped?

**Comment by AaronErhardt** [comment]
```
Mär 02 09:14:50 - tux-tailord[1169]:  INFO tux_tailord: Received a shutdown signal
Mär 02 09:14:50 - tux-tailord[1169]:  INFO tux_tailord: Shutting down, bye!
Mär 02 09:14:51 - systemd[1]: tailord.service: Main process exited, code=dumped, status=6/ABRT
Mär 02 09:14:51 - systemd[1]: tailord.service: Failed with result 'core-dump'.
Mär 02 09:14:51 - systemd[1]: tailord.service: Consumed 3min 51.386s CPU time.
```

This is what I get when I use the kill command. So the INT signal is caught, but for some reason the core is still dumped afterwards. I'm not entirely sure why though, but so far I've just been ignoring it since apparently the shutdown works as expected...

**Comment by crisidev** [comment]
Ok. In my system the signal is never caught. I believe I am doing something wrong that is blocking the uring event loop.

**Comment by wvengen** [comment]
I have a InfinityBook Pro 14 Gen6, and am getting a similar error as in https://github.com/AaronErhardt/tuxedo-rs/issues/2#issue-1463458408 in `tailord/src/keyboard/runtime.rs:18:49`. If you like to share you (however hackish) patches, I'd be happy to do some tinkering as well.

**Comment by crisidev** [comment]
I'll push everything I have on a fork today.

**Comment by crisidev** [comment]
https://github.com/AaronErhardt/tuxedo-rs/compare/main...crisidev:tuxedo-rs:main

**Comment by crisidev** [comment]
It's ugly and broke, I'll find some time to continue experimenting hopefully next week.

**Comment by wvengen** [comment]
Awesome, thank you! At least I can get the daemon running now.

**Comment by crisidev** [comment]
There is something in the HW management that is not letting the daemon run properly. Signals are not caught and the shared channels get closed and return errors after a while. I don't know what I did wrong so far :D

**Comment by AaronErhardt** [comment]
@crisidev did you have time to try out my patch to address the suspend problems? https://github.com/crisidev/tuxedo-rs/pull/1
I'm interested to hear what results you get and whether there are still issues.

**Comment by crisidev** [comment]
I am letting this run in debug for a while, but it hasn't crashed or reported closed channels yet after your patch..

**Comment by AaronErhardt** [comment]
@crisidev how has it going? I hope you've had a great experience with tailord over the last week :)

I'd like to upstream your changes soon if you don't mind. Tailor GUI is in a good state meanwhile, so want to finally announce tuxedo-rs, but hopefully we can get uniwill support merged before.

**Comment by crisidev** [comment]
I haven't had too much time to test it, but it seems to be working properly. I have allocated some time for this weekend to work on the PR to support uniwill, sorry for the delay :) I hope to have something cleaned up for you soon.

**Comment by crisidev** [comment]
There are more things to support but the basic is there!
